/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 07 19:19:29 GMT 2019
 */

package model;

import org.junit.Test;
import static org.junit.Assert.*;
import model.AddRelationException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AddRelationException_ESTest extends model.AddRelationException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AddRelationException addRelationException0 = new AddRelationException((String) null);
  }
}
