/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 02 23:49:25 GMT 2019
 */

package model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.SimpleTimeZone;
import java.util.TimeZone;
import java.util.Vector;
import model.Person;
import model.Relation;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockCalendar;
import org.evosuite.runtime.mock.java.util.MockGregorianCalendar;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Person_ESTest extends model.Person_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, true);
      assertEquals(1, person0.getId());
      assertNull(person0.getFirstName());
      assertEquals("female", person0.getGender());
      assertEquals(1, person0.getGenderAsInt());
      assertNull(person0.getLastName());
      assertTrue(person0.isFemale());
      assertNotNull(person0);
      
      GregorianCalendar gregorianCalendar0 = person0.getDateOfBirth();
      assertEquals(1, person0.getId());
      assertNull(person0.getFirstName());
      assertEquals("female", person0.getGender());
      assertEquals(1, person0.getGenderAsInt());
      assertNull(person0.getLastName());
      assertTrue(person0.isFemale());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertTrue(gregorianCalendar0.isLenient());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=?,MONTH=?,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=?,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=?,HOUR=?,HOUR_OF_DAY=?,MINUTE=?,SECOND=?,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      assertNotNull(gregorianCalendar0);
      
      gregorianCalendar0.add(1, 1);
      assertEquals(1, person0.getId());
      assertNull(person0.getFirstName());
      assertEquals("female", person0.getGender());
      assertEquals(1, person0.getGenderAsInt());
      assertNull(person0.getLastName());
      assertTrue(person0.isFemale());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=1971,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertTrue(gregorianCalendar0.isLenient());
      
      boolean boolean0 = person0.dateOfDeathEquals(gregorianCalendar0);
      assertEquals(1, person0.getId());
      assertNull(person0.getFirstName());
      assertEquals("female", person0.getGender());
      assertEquals(1, person0.getGenderAsInt());
      assertNull(person0.getLastName());
      assertTrue(person0.isFemale());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=1971,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertTrue(gregorianCalendar0.isLenient());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Person person0 = Person.restorePerson(264, "4xevA5645!", "4xevA5645!", false);
      assertEquals(0, person0.getGenderAsInt());
      assertEquals("4xevA5645!", person0.getFirstName());
      assertEquals("male", person0.getGender());
      assertEquals(264, person0.getId());
      assertFalse(person0.isFemale());
      assertEquals("4xevA5645!", person0.getLastName());
      assertNotNull(person0);
      
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar(264, 264, 5122, 5122, 5122, 264);
      assertNotNull(mockGregorianCalendar0);
      
      person0.setDateOfDeath(mockGregorianCalendar0);
      assertEquals(0, person0.getGenderAsInt());
      assertEquals("4xevA5645!", person0.getFirstName());
      assertEquals("male", person0.getGender());
      assertEquals(264, person0.getId());
      assertFalse(person0.isFemale());
      assertEquals("4xevA5645!", person0.getLastName());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=264,MONTH=264,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=5122,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=5122,HOUR_OF_DAY=5122,MINUTE=5122,SECOND=264,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", mockGregorianCalendar0.toString());
      assertTrue(mockGregorianCalendar0.isLenient());
      assertEquals(1, mockGregorianCalendar0.getFirstDayOfWeek());
      assertEquals(1, mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      
      MockGregorianCalendar mockGregorianCalendar1 = new MockGregorianCalendar(0, 1115, 979);
      assertTrue(mockGregorianCalendar1.equals((Object)mockGregorianCalendar0));
      assertNotNull(mockGregorianCalendar1);
      
      boolean boolean0 = person0.dateOfDeathEquals(mockGregorianCalendar1);
      assertEquals(0, person0.getGenderAsInt());
      assertEquals("4xevA5645!", person0.getFirstName());
      assertEquals("male", person0.getGender());
      assertEquals(264, person0.getId());
      assertFalse(person0.isFemale());
      assertEquals("4xevA5645!", person0.getLastName());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=0,MONTH=1115,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=979,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", mockGregorianCalendar1.toString());
      assertTrue(mockGregorianCalendar1.isLenient());
      assertEquals(1, mockGregorianCalendar1.getFirstDayOfWeek());
      assertEquals(1, mockGregorianCalendar1.getMinimalDaysInFirstWeek());
      assertNotSame(mockGregorianCalendar1, mockGregorianCalendar0);
      assertTrue(mockGregorianCalendar1.equals((Object)mockGregorianCalendar0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, true);
      assertEquals(1, person0.getId());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertNull(person0.getLastName());
      assertNull(person0.getFirstName());
      assertNotNull(person0);
      
      GregorianCalendar gregorianCalendar0 = person0.getDateOfBirth();
      assertEquals(1, person0.getId());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertNull(person0.getLastName());
      assertNull(person0.getFirstName());
      assertTrue(gregorianCalendar0.isLenient());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=?,MONTH=?,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=?,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=?,HOUR=?,HOUR_OF_DAY=?,MINUTE=?,SECOND=?,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      assertNotNull(gregorianCalendar0);
      
      gregorianCalendar0.add(1, 1);
      assertEquals(1, person0.getId());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertNull(person0.getLastName());
      assertNull(person0.getFirstName());
      assertTrue(gregorianCalendar0.isLenient());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=1971,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      
      boolean boolean0 = person0.dateOfBirthEquals(gregorianCalendar0);
      assertEquals(1, person0.getId());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertNull(person0.getLastName());
      assertNull(person0.getFirstName());
      assertTrue(gregorianCalendar0.isLenient());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=1971,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Person person0 = new Person("Relation exists or is illegal", "Relation exists or is illegal", true);
      assertEquals("Relation exists or is illegal", person0.getLastName());
      assertEquals("Relation exists or is illegal", person0.getFirstName());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals(1, person0.getId());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertNotNull(person0);
      
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar();
      assertNotNull(mockGregorianCalendar0);
      
      person0.setDateOfBirth(mockGregorianCalendar0);
      assertEquals("Relation exists or is illegal", person0.getLastName());
      assertEquals("Relation exists or is illegal", person0.getFirstName());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals(1, person0.getId());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertEquals(1, mockGregorianCalendar0.getFirstDayOfWeek());
      assertTrue(mockGregorianCalendar0.isLenient());
      assertEquals(1, mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=1392409281320,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2014,MONTH=1,WEEK_OF_YEAR=7,WEEK_OF_MONTH=3,DAY_OF_MONTH=14,DAY_OF_YEAR=45,DAY_OF_WEEK=6,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=8,HOUR_OF_DAY=20,MINUTE=21,SECOND=21,MILLISECOND=320,ZONE_OFFSET=0,DST_OFFSET=0]", mockGregorianCalendar0.toString());
      
      MockGregorianCalendar mockGregorianCalendar1 = new MockGregorianCalendar(1, 2, 1, (-2666), 1);
      assertFalse(mockGregorianCalendar1.equals((Object)mockGregorianCalendar0));
      assertNotNull(mockGregorianCalendar1);
      
      boolean boolean0 = person0.dateOfBirthEquals(mockGregorianCalendar1);
      assertEquals("Relation exists or is illegal", person0.getLastName());
      assertEquals("Relation exists or is illegal", person0.getFirstName());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals(1, person0.getId());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertTrue(mockGregorianCalendar1.isLenient());
      assertEquals(1, mockGregorianCalendar1.getFirstDayOfWeek());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=1,MONTH=2,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=1,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=-2666,HOUR_OF_DAY=-2666,MINUTE=1,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", mockGregorianCalendar1.toString());
      assertEquals(1, mockGregorianCalendar1.getMinimalDaysInFirstWeek());
      assertNotSame(mockGregorianCalendar1, mockGregorianCalendar0);
      assertFalse(mockGregorianCalendar1.equals((Object)mockGregorianCalendar0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "", " ", true);
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals(0, person0.getId());
      assertEquals("female", person0.getGender());
      assertEquals(" ", person0.getLastName());
      assertEquals("", person0.getFirstName());
      assertNotNull(person0);
      
      boolean boolean0 = person0.isFemale();
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals(0, person0.getId());
      assertEquals("female", person0.getGender());
      assertEquals(" ", person0.getLastName());
      assertEquals("", person0.getFirstName());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "Father", "Father", true);
      assertEquals("Father", person0.getLastName());
      assertEquals("Father", person0.getFirstName());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals(0, person0.getId());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertNotNull(person0);
      
      Person person1 = new Person("female", "female", true);
      assertEquals("female", person1.getLastName());
      assertTrue(person1.isFemale());
      assertEquals(2, person1.getId());
      assertEquals("female", person1.getFirstName());
      assertEquals(1, person1.getGenderAsInt());
      assertEquals("female", person1.getGender());
      assertFalse(person1.equals((Object)person0));
      assertNotNull(person1);
      
      person0.addChild(person1);
      assertEquals("Father", person0.getLastName());
      assertEquals("Father", person0.getFirstName());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals(0, person0.getId());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertEquals("female", person1.getLastName());
      assertTrue(person1.isFemale());
      assertEquals(2, person1.getId());
      assertEquals("female", person1.getFirstName());
      assertEquals(1, person1.getGenderAsInt());
      assertEquals("female", person1.getGender());
      assertNotSame(person0, person1);
      assertNotSame(person1, person0);
      assertFalse(person0.equals((Object)person1));
      assertFalse(person1.equals((Object)person0));
      
      Vector vector0 = person1.getRelationships();
      assertEquals("female", person1.getLastName());
      assertTrue(person1.isFemale());
      assertEquals(2, person1.getId());
      assertEquals("female", person1.getFirstName());
      assertEquals(1, person1.getGenderAsInt());
      assertEquals("female", person1.getGender());
      assertEquals(10, vector0.capacity());
      assertEquals(1, vector0.size());
      assertFalse(vector0.isEmpty());
      assertNotSame(person1, person0);
      assertFalse(person1.equals((Object)person0));
      assertNotNull(vector0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Person person0 = new Person("", (String) null, false);
      assertEquals(1, person0.getId());
      assertFalse(person0.isFemale());
      assertEquals("male", person0.getGender());
      assertNull(person0.getLastName());
      assertEquals("", person0.getFirstName());
      assertEquals(0, person0.getGenderAsInt());
      assertNotNull(person0);
      
      String string0 = person0.getLastName();
      assertEquals(1, person0.getId());
      assertFalse(person0.isFemale());
      assertEquals("male", person0.getGender());
      assertNull(person0.getLastName());
      assertEquals("", person0.getFirstName());
      assertEquals(0, person0.getGenderAsInt());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Person person0 = Person.restorePerson(0, " ", "", false);
      assertEquals(0, person0.getGenderAsInt());
      assertFalse(person0.isFemale());
      assertEquals("male", person0.getGender());
      assertEquals("", person0.getLastName());
      assertEquals(" ", person0.getFirstName());
      assertEquals(0, person0.getId());
      assertNotNull(person0);
      
      String string0 = person0.getLastName();
      assertEquals(0, person0.getGenderAsInt());
      assertFalse(person0.isFemale());
      assertEquals("male", person0.getGender());
      assertEquals("", person0.getLastName());
      assertEquals(" ", person0.getFirstName());
      assertEquals(0, person0.getId());
      assertEquals("", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "", "", true);
      assertEquals(0, person0.getId());
      assertEquals("", person0.getFirstName());
      assertEquals("female", person0.getGender());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("", person0.getLastName());
      assertTrue(person0.isFemale());
      assertNotNull(person0);
      
      int int0 = person0.getId();
      assertEquals(0, person0.getId());
      assertEquals("", person0.getFirstName());
      assertEquals("female", person0.getGender());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("", person0.getLastName());
      assertTrue(person0.isFemale());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Person person0 = Person.restorePerson((-2643), "", "", true);
      assertEquals((-2643), person0.getId());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("", person0.getLastName());
      assertEquals("", person0.getFirstName());
      assertNotNull(person0);
      
      int int0 = person0.getId();
      assertEquals((-2643), person0.getId());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("", person0.getLastName());
      assertEquals("", person0.getFirstName());
      assertEquals((-2643), int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, true);
      assertNull(person0.getFirstName());
      assertEquals(1, person0.getGenderAsInt());
      assertNull(person0.getLastName());
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getId());
      assertEquals("female", person0.getGender());
      assertNotNull(person0);
      
      String string0 = person0.getFirstName();
      assertNull(person0.getFirstName());
      assertEquals(1, person0.getGenderAsInt());
      assertNull(person0.getLastName());
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getId());
      assertEquals("female", person0.getGender());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Person person0 = new Person("", "", false);
      assertEquals(0, person0.getGenderAsInt());
      assertEquals(1, person0.getId());
      assertEquals("", person0.getLastName());
      assertFalse(person0.isFemale());
      assertEquals("", person0.getFirstName());
      assertEquals("male", person0.getGender());
      assertNotNull(person0);
      
      String string0 = person0.getFirstName();
      assertEquals(0, person0.getGenderAsInt());
      assertEquals(1, person0.getId());
      assertEquals("", person0.getLastName());
      assertFalse(person0.isFemale());
      assertEquals("", person0.getFirstName());
      assertEquals("male", person0.getGender());
      assertEquals("", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Person person0 = Person.restorePerson(10, "/(>kAm6\"S,w", "/(>kAm6\"S,w", false);
      assertEquals("male", person0.getGender());
      assertFalse(person0.isFemale());
      assertEquals(0, person0.getGenderAsInt());
      assertEquals("/(>kAm6\"S,w", person0.getFirstName());
      assertEquals(10, person0.getId());
      assertEquals("/(>kAm6\"S,w", person0.getLastName());
      assertNotNull(person0);
      
      SimpleTimeZone simpleTimeZone0 = new SimpleTimeZone(3882, "A.*gb&|WEO");
      assertEquals("A.*gb&|WEO", simpleTimeZone0.getID());
      assertEquals("java.util.SimpleTimeZone[id=A.*gb&|WEO,offset=3882,dstSavings=3600000,useDaylight=false,startYear=0,startMode=0,startMonth=0,startDay=0,startDayOfWeek=0,startTime=0,startTimeMode=0,endMode=0,endMonth=0,endDay=0,endDayOfWeek=0,endTime=0,endTimeMode=0]", simpleTimeZone0.toString());
      assertEquals(0, simpleTimeZone0.getDSTSavings());
      assertEquals(3882, simpleTimeZone0.getRawOffset());
      assertFalse(simpleTimeZone0.useDaylightTime());
      assertNotNull(simpleTimeZone0);
      
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar(simpleTimeZone0);
      assertNotNull(mockGregorianCalendar0);
      
      person0.setDateOfDeath(mockGregorianCalendar0);
      assertEquals("male", person0.getGender());
      assertFalse(person0.isFemale());
      assertEquals(0, person0.getGenderAsInt());
      assertEquals("/(>kAm6\"S,w", person0.getFirstName());
      assertEquals(10, person0.getId());
      assertEquals("/(>kAm6\"S,w", person0.getLastName());
      assertEquals("A.*gb&|WEO", simpleTimeZone0.getID());
      assertEquals("java.util.SimpleTimeZone[id=A.*gb&|WEO,offset=3882,dstSavings=3600000,useDaylight=false,startYear=0,startMode=0,startMonth=0,startDay=0,startDayOfWeek=0,startTime=0,startTimeMode=0,endMode=0,endMonth=0,endDay=0,endDayOfWeek=0,endTime=0,endTimeMode=0]", simpleTimeZone0.toString());
      assertEquals(0, simpleTimeZone0.getDSTSavings());
      assertEquals(3882, simpleTimeZone0.getRawOffset());
      assertFalse(simpleTimeZone0.useDaylightTime());
      assertTrue(mockGregorianCalendar0.isLenient());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=1392409281320,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=java.util.SimpleTimeZone[id=A.*gb&|WEO,offset=3882,dstSavings=3600000,useDaylight=false,startYear=0,startMode=0,startMonth=0,startDay=0,startDayOfWeek=0,startTime=0,startTimeMode=0,endMode=0,endMonth=0,endDay=0,endDayOfWeek=0,endTime=0,endTimeMode=0],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2014,MONTH=1,WEEK_OF_YEAR=7,WEEK_OF_MONTH=3,DAY_OF_MONTH=14,DAY_OF_YEAR=45,DAY_OF_WEEK=6,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=8,HOUR_OF_DAY=20,MINUTE=21,SECOND=25,MILLISECOND=202,ZONE_OFFSET=3882,DST_OFFSET=0]", mockGregorianCalendar0.toString());
      assertEquals(1, mockGregorianCalendar0.getFirstDayOfWeek());
      assertEquals(1, mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      
      mockGregorianCalendar0.setLenient(false);
      assertEquals("A.*gb&|WEO", simpleTimeZone0.getID());
      assertEquals("java.util.SimpleTimeZone[id=A.*gb&|WEO,offset=3882,dstSavings=3600000,useDaylight=false,startYear=0,startMode=0,startMonth=0,startDay=0,startDayOfWeek=0,startTime=0,startTimeMode=0,endMode=0,endMonth=0,endDay=0,endDayOfWeek=0,endTime=0,endTimeMode=0]", simpleTimeZone0.toString());
      assertEquals(0, simpleTimeZone0.getDSTSavings());
      assertEquals(3882, simpleTimeZone0.getRawOffset());
      assertFalse(simpleTimeZone0.useDaylightTime());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=1392409281320,areFieldsSet=true,areAllFieldsSet=true,lenient=false,zone=java.util.SimpleTimeZone[id=A.*gb&|WEO,offset=3882,dstSavings=3600000,useDaylight=false,startYear=0,startMode=0,startMonth=0,startDay=0,startDayOfWeek=0,startTime=0,startTimeMode=0,endMode=0,endMonth=0,endDay=0,endDayOfWeek=0,endTime=0,endTimeMode=0],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2014,MONTH=1,WEEK_OF_YEAR=7,WEEK_OF_MONTH=3,DAY_OF_MONTH=14,DAY_OF_YEAR=45,DAY_OF_WEEK=6,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=8,HOUR_OF_DAY=20,MINUTE=21,SECOND=25,MILLISECOND=202,ZONE_OFFSET=3882,DST_OFFSET=0]", mockGregorianCalendar0.toString());
      assertEquals(1, mockGregorianCalendar0.getFirstDayOfWeek());
      assertEquals(1, mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      assertFalse(mockGregorianCalendar0.isLenient());
      
      GregorianCalendar gregorianCalendar0 = person0.getDateOfDeath();
      assertEquals("male", person0.getGender());
      assertFalse(person0.isFemale());
      assertEquals(0, person0.getGenderAsInt());
      assertEquals("/(>kAm6\"S,w", person0.getFirstName());
      assertEquals(10, person0.getId());
      assertEquals("/(>kAm6\"S,w", person0.getLastName());
      assertFalse(gregorianCalendar0.isLenient());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=1392409281320,areFieldsSet=true,areAllFieldsSet=true,lenient=false,zone=java.util.SimpleTimeZone[id=A.*gb&|WEO,offset=3882,dstSavings=3600000,useDaylight=false,startYear=0,startMode=0,startMonth=0,startDay=0,startDayOfWeek=0,startTime=0,startTimeMode=0,endMode=0,endMonth=0,endDay=0,endDayOfWeek=0,endTime=0,endTimeMode=0],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2014,MONTH=1,WEEK_OF_YEAR=7,WEEK_OF_MONTH=3,DAY_OF_MONTH=14,DAY_OF_YEAR=45,DAY_OF_WEEK=6,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=8,HOUR_OF_DAY=20,MINUTE=21,SECOND=25,MILLISECOND=202,ZONE_OFFSET=3882,DST_OFFSET=0]", gregorianCalendar0.toString());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertNotSame(gregorianCalendar0, mockGregorianCalendar0);
      assertTrue(gregorianCalendar0.equals((Object)mockGregorianCalendar0));
      assertNotNull(gregorianCalendar0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "", " ", true);
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("", person0.getFirstName());
      assertEquals(" ", person0.getLastName());
      assertEquals(0, person0.getId());
      assertEquals("female", person0.getGender());
      assertNotNull(person0);
      
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar();
      assertNotNull(mockGregorianCalendar0);
      
      mockGregorianCalendar0.setFirstDayOfWeek((-830));
      assertEquals(1, mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals((-830), mockGregorianCalendar0.getFirstDayOfWeek());
      assertTrue(mockGregorianCalendar0.isLenient());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=1392409281320,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=-830,minimalDaysInFirstWeek=1,ERA=1,YEAR=2014,MONTH=1,WEEK_OF_YEAR=7,WEEK_OF_MONTH=3,DAY_OF_MONTH=14,DAY_OF_YEAR=45,DAY_OF_WEEK=6,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=8,HOUR_OF_DAY=20,MINUTE=21,SECOND=21,MILLISECOND=320,ZONE_OFFSET=0,DST_OFFSET=0]", mockGregorianCalendar0.toString());
      
      person0.setDateOfDeath(mockGregorianCalendar0);
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("", person0.getFirstName());
      assertEquals(" ", person0.getLastName());
      assertEquals(0, person0.getId());
      assertEquals("female", person0.getGender());
      assertEquals(1, mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals((-830), mockGregorianCalendar0.getFirstDayOfWeek());
      assertTrue(mockGregorianCalendar0.isLenient());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=1392409281320,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=-830,minimalDaysInFirstWeek=1,ERA=1,YEAR=2014,MONTH=1,WEEK_OF_YEAR=7,WEEK_OF_MONTH=3,DAY_OF_MONTH=14,DAY_OF_YEAR=45,DAY_OF_WEEK=6,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=8,HOUR_OF_DAY=20,MINUTE=21,SECOND=21,MILLISECOND=320,ZONE_OFFSET=0,DST_OFFSET=0]", mockGregorianCalendar0.toString());
      
      GregorianCalendar gregorianCalendar0 = person0.getDateOfDeath();
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("", person0.getFirstName());
      assertEquals(" ", person0.getLastName());
      assertEquals(0, person0.getId());
      assertEquals("female", person0.getGender());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=1392409281320,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=-830,minimalDaysInFirstWeek=1,ERA=1,YEAR=2014,MONTH=1,WEEK_OF_YEAR=7,WEEK_OF_MONTH=3,DAY_OF_MONTH=14,DAY_OF_YEAR=45,DAY_OF_WEEK=6,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=8,HOUR_OF_DAY=20,MINUTE=21,SECOND=21,MILLISECOND=320,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      assertTrue(gregorianCalendar0.isLenient());
      assertEquals((-830), gregorianCalendar0.getFirstDayOfWeek());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertNotSame(gregorianCalendar0, mockGregorianCalendar0);
      assertTrue(gregorianCalendar0.equals((Object)mockGregorianCalendar0));
      assertNotNull(gregorianCalendar0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Person person0 = Person.restorePerson(292, "", "72rDO", true);
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("", person0.getFirstName());
      assertEquals("72rDO", person0.getLastName());
      assertEquals(292, person0.getId());
      assertEquals("female", person0.getGender());
      assertNotNull(person0);
      
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar(292, (-2331), (-2331));
      assertNotNull(mockGregorianCalendar0);
      
      mockGregorianCalendar0.setLenient(false);
      assertEquals(1, mockGregorianCalendar0.getFirstDayOfWeek());
      assertFalse(mockGregorianCalendar0.isLenient());
      assertEquals(1, mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=false,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=292,MONTH=-2331,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=-2331,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", mockGregorianCalendar0.toString());
      
      person0.setDateOfBirth(mockGregorianCalendar0);
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("", person0.getFirstName());
      assertEquals("72rDO", person0.getLastName());
      assertEquals(292, person0.getId());
      assertEquals("female", person0.getGender());
      assertEquals(1, mockGregorianCalendar0.getFirstDayOfWeek());
      assertFalse(mockGregorianCalendar0.isLenient());
      assertEquals(1, mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=false,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=292,MONTH=-2331,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=-2331,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", mockGregorianCalendar0.toString());
      
      GregorianCalendar gregorianCalendar0 = person0.getDateOfBirth();
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("", person0.getFirstName());
      assertEquals("72rDO", person0.getLastName());
      assertEquals(292, person0.getId());
      assertEquals("female", person0.getGender());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=false,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=292,MONTH=-2331,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=-2331,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertFalse(gregorianCalendar0.isLenient());
      assertNotSame(gregorianCalendar0, mockGregorianCalendar0);
      assertTrue(gregorianCalendar0.equals((Object)mockGregorianCalendar0));
      assertNotNull(gregorianCalendar0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Person person0 = Person.restorePerson((-1618), "&%j)M(ei,a7KADd$u", "&%j)M(ei,a7KADd$u", true);
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertEquals("&%j)M(ei,a7KADd$u", person0.getFirstName());
      assertEquals((-1618), person0.getId());
      assertEquals("&%j)M(ei,a7KADd$u", person0.getLastName());
      assertNotNull(person0);
      
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar((-1016), 15, 0);
      assertNotNull(mockGregorianCalendar0);
      
      mockGregorianCalendar0.setMinimalDaysInFirstWeek(0);
      assertEquals(0, mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      assertTrue(mockGregorianCalendar0.isLenient());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=0,ERA=?,YEAR=-1016,MONTH=15,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=0,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", mockGregorianCalendar0.toString());
      assertEquals(1, mockGregorianCalendar0.getFirstDayOfWeek());
      
      person0.setDateOfBirth(mockGregorianCalendar0);
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertEquals("&%j)M(ei,a7KADd$u", person0.getFirstName());
      assertEquals((-1618), person0.getId());
      assertEquals("&%j)M(ei,a7KADd$u", person0.getLastName());
      assertEquals(0, mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      assertTrue(mockGregorianCalendar0.isLenient());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=0,ERA=?,YEAR=-1016,MONTH=15,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=0,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", mockGregorianCalendar0.toString());
      assertEquals(1, mockGregorianCalendar0.getFirstDayOfWeek());
      
      GregorianCalendar gregorianCalendar0 = person0.getDateOfBirth();
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertEquals("&%j)M(ei,a7KADd$u", person0.getFirstName());
      assertEquals((-1618), person0.getId());
      assertEquals("&%j)M(ei,a7KADd$u", person0.getLastName());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=0,ERA=?,YEAR=-1016,MONTH=15,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=0,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      assertEquals(0, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertTrue(gregorianCalendar0.isLenient());
      assertNotSame(gregorianCalendar0, mockGregorianCalendar0);
      assertTrue(gregorianCalendar0.equals((Object)mockGregorianCalendar0));
      assertNotNull(gregorianCalendar0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Person person0 = new Person("", "male", true);
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getId());
      assertEquals("male", person0.getLastName());
      assertEquals("", person0.getFirstName());
      assertNotNull(person0);
      
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar();
      assertNotNull(mockGregorianCalendar0);
      
      person0.setDateOfBirth(mockGregorianCalendar0);
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getId());
      assertEquals("male", person0.getLastName());
      assertEquals("", person0.getFirstName());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=1392409281320,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2014,MONTH=1,WEEK_OF_YEAR=7,WEEK_OF_MONTH=3,DAY_OF_MONTH=14,DAY_OF_YEAR=45,DAY_OF_WEEK=6,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=8,HOUR_OF_DAY=20,MINUTE=21,SECOND=21,MILLISECOND=320,ZONE_OFFSET=0,DST_OFFSET=0]", mockGregorianCalendar0.toString());
      assertEquals(1, mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, mockGregorianCalendar0.getFirstDayOfWeek());
      assertTrue(mockGregorianCalendar0.isLenient());
      
      mockGregorianCalendar0.setMinimalDaysInFirstWeek((-1));
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=1392409281320,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=-1,ERA=1,YEAR=2014,MONTH=1,WEEK_OF_YEAR=7,WEEK_OF_MONTH=3,DAY_OF_MONTH=14,DAY_OF_YEAR=45,DAY_OF_WEEK=6,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=8,HOUR_OF_DAY=20,MINUTE=21,SECOND=21,MILLISECOND=320,ZONE_OFFSET=0,DST_OFFSET=0]", mockGregorianCalendar0.toString());
      assertEquals((-1), mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, mockGregorianCalendar0.getFirstDayOfWeek());
      assertTrue(mockGregorianCalendar0.isLenient());
      
      GregorianCalendar gregorianCalendar0 = person0.getDateOfBirth();
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getId());
      assertEquals("male", person0.getLastName());
      assertEquals("", person0.getFirstName());
      assertEquals((-1), gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=1392409281320,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=-1,ERA=1,YEAR=2014,MONTH=1,WEEK_OF_YEAR=7,WEEK_OF_MONTH=3,DAY_OF_MONTH=14,DAY_OF_YEAR=45,DAY_OF_WEEK=6,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=8,HOUR_OF_DAY=20,MINUTE=21,SECOND=21,MILLISECOND=320,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      assertTrue(gregorianCalendar0.isLenient());
      assertNotSame(gregorianCalendar0, mockGregorianCalendar0);
      assertTrue(gregorianCalendar0.equals((Object)mockGregorianCalendar0));
      assertNotNull(gregorianCalendar0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Person person0 = Person.restorePerson((-1895), "AWRAPpY99~ECQ9~p!", "R!0I{R\"HIBu\"", false);
      assertEquals((-1895), person0.getId());
      assertEquals("male", person0.getGender());
      assertEquals(0, person0.getGenderAsInt());
      assertEquals("AWRAPpY99~ECQ9~p!", person0.getFirstName());
      assertFalse(person0.isFemale());
      assertEquals("R!0I{R\"HIBu\"", person0.getLastName());
      assertNotNull(person0);
      
      person0.setDateOfDeath((GregorianCalendar) null);
      assertEquals((-1895), person0.getId());
      assertEquals("male", person0.getGender());
      assertEquals(0, person0.getGenderAsInt());
      assertEquals("AWRAPpY99~ECQ9~p!", person0.getFirstName());
      assertFalse(person0.isFemale());
      assertEquals("R!0I{R\"HIBu\"", person0.getLastName());
      
      // Undeclared exception!
      try { 
        person0.getDateOfDeath();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("model.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Person person0 = new Person((String) null, "", false);
      assertEquals(1, person0.getId());
      assertNull(person0.getFirstName());
      assertEquals(0, person0.getGenderAsInt());
      assertEquals("", person0.getLastName());
      assertFalse(person0.isFemale());
      assertEquals("male", person0.getGender());
      assertNotNull(person0);
      
      person0.setDateOfBirth((GregorianCalendar) null);
      assertEquals(1, person0.getId());
      assertNull(person0.getFirstName());
      assertEquals(0, person0.getGenderAsInt());
      assertEquals("", person0.getLastName());
      assertFalse(person0.isFemale());
      assertEquals("male", person0.getGender());
      
      // Undeclared exception!
      try { 
        person0.getDateOfBirth();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("model.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, true);
      assertNull(person0.getLastName());
      assertEquals(1, person0.getGenderAsInt());
      assertTrue(person0.isFemale());
      assertNull(person0.getFirstName());
      assertEquals(1, person0.getId());
      assertEquals("female", person0.getGender());
      assertNotNull(person0);
      
      person0.setDateOfDeath((GregorianCalendar) null);
      assertNull(person0.getLastName());
      assertEquals(1, person0.getGenderAsInt());
      assertTrue(person0.isFemale());
      assertNull(person0.getFirstName());
      assertEquals(1, person0.getId());
      assertEquals("female", person0.getGender());
      
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar(0, (-1086), 0, (-1086), (-1086));
      assertNotNull(mockGregorianCalendar0);
      
      // Undeclared exception!
      try { 
        person0.dateOfDeathEquals(mockGregorianCalendar0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("model.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Person person0 = new Person("plxn7N", "plxn7N", true);
      assertTrue(person0.isFemale());
      assertEquals("female", person0.getGender());
      assertEquals("plxn7N", person0.getFirstName());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("plxn7N", person0.getLastName());
      assertEquals(1, person0.getId());
      assertNotNull(person0);
      
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar(1180, 2848, (-253));
      assertNotNull(mockGregorianCalendar0);
      
      mockGregorianCalendar0.setLenient(false);
      assertEquals(1, mockGregorianCalendar0.getFirstDayOfWeek());
      assertEquals(1, mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=false,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=1180,MONTH=2848,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=-253,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", mockGregorianCalendar0.toString());
      assertFalse(mockGregorianCalendar0.isLenient());
      
      // Undeclared exception!
      try { 
        person0.dateOfDeathEquals(mockGregorianCalendar0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // MONTH
         //
         verifyException("java.util.GregorianCalendar", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Person person0 = Person.restorePerson((-1), "+ciK9cL!", "asI(a}JDvF0", false);
      assertFalse(person0.isFemale());
      assertEquals((-1), person0.getId());
      assertEquals("male", person0.getGender());
      assertEquals("asI(a}JDvF0", person0.getLastName());
      assertEquals("+ciK9cL!", person0.getFirstName());
      assertEquals(0, person0.getGenderAsInt());
      assertNotNull(person0);
      
      Locale locale0 = Locale.FRANCE;
      assertEquals("fr", locale0.getLanguage());
      assertEquals("FR", locale0.getCountry());
      assertEquals("FRA", locale0.getISO3Country());
      assertEquals("", locale0.getVariant());
      assertEquals("fra", locale0.getISO3Language());
      assertEquals("fr_FR", locale0.toString());
      assertNotNull(locale0);
      
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar(locale0);
      assertNotNull(mockGregorianCalendar0);
      
      mockGregorianCalendar0.setTimeZone((TimeZone) null);
      assertEquals("fr", locale0.getLanguage());
      assertEquals("FR", locale0.getCountry());
      assertEquals("FRA", locale0.getISO3Country());
      assertEquals("", locale0.getVariant());
      assertEquals("fra", locale0.getISO3Language());
      assertEquals("fr_FR", locale0.toString());
      assertEquals(4, mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=1392409281320,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=null,firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=1,YEAR=2014,MONTH=1,WEEK_OF_YEAR=7,WEEK_OF_MONTH=2,DAY_OF_MONTH=14,DAY_OF_YEAR=45,DAY_OF_WEEK=6,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=8,HOUR_OF_DAY=20,MINUTE=21,SECOND=21,MILLISECOND=320,ZONE_OFFSET=0,DST_OFFSET=0]", mockGregorianCalendar0.toString());
      assertEquals(2, mockGregorianCalendar0.getFirstDayOfWeek());
      assertTrue(mockGregorianCalendar0.isLenient());
      
      // Undeclared exception!
      try { 
        person0.dateOfBirthEquals(mockGregorianCalendar0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Person person0 = Person.restorePerson(2909, "zkd", "zkd", true);
      assertEquals("zkd", person0.getLastName());
      assertEquals("zkd", person0.getFirstName());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertEquals(2909, person0.getId());
      assertNotNull(person0);
      
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar();
      assertNotNull(mockGregorianCalendar0);
      
      mockGregorianCalendar0.setLenient(false);
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=1392409281320,areFieldsSet=true,areAllFieldsSet=true,lenient=false,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2014,MONTH=1,WEEK_OF_YEAR=7,WEEK_OF_MONTH=3,DAY_OF_MONTH=14,DAY_OF_YEAR=45,DAY_OF_WEEK=6,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=8,HOUR_OF_DAY=20,MINUTE=21,SECOND=21,MILLISECOND=320,ZONE_OFFSET=0,DST_OFFSET=0]", mockGregorianCalendar0.toString());
      assertFalse(mockGregorianCalendar0.isLenient());
      assertEquals(1, mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, mockGregorianCalendar0.getFirstDayOfWeek());
      
      mockGregorianCalendar0.set(2909, 2909, 2909);
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=true,lenient=false,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2909,MONTH=2909,WEEK_OF_YEAR=7,WEEK_OF_MONTH=3,DAY_OF_MONTH=2909,DAY_OF_YEAR=45,DAY_OF_WEEK=6,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=8,HOUR_OF_DAY=20,MINUTE=21,SECOND=21,MILLISECOND=320,ZONE_OFFSET=0,DST_OFFSET=0]", mockGregorianCalendar0.toString());
      assertFalse(mockGregorianCalendar0.isLenient());
      assertEquals(1, mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, mockGregorianCalendar0.getFirstDayOfWeek());
      
      // Undeclared exception!
      try { 
        person0.dateOfBirthEquals(mockGregorianCalendar0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // MONTH
         //
         verifyException("java.util.GregorianCalendar", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Person person0 = new Person("model.AddRelationException", "model.AddRelationException", true);
      assertEquals("model.AddRelationException", person0.getFirstName());
      assertTrue(person0.isFemale());
      assertEquals("model.AddRelationException", person0.getLastName());
      assertEquals(1, person0.getId());
      assertEquals("female", person0.getGender());
      assertEquals(1, person0.getGenderAsInt());
      assertNotNull(person0);
      
      // Undeclared exception!
      try { 
        person0.addSpouse((Person) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("model.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, false);
      assertFalse(person0.isFemale());
      assertNull(person0.getLastName());
      assertEquals(0, person0.getGenderAsInt());
      assertEquals(1, person0.getId());
      assertNull(person0.getFirstName());
      assertEquals("male", person0.getGender());
      assertNotNull(person0);
      
      // Undeclared exception!
      try { 
        person0.addChild((Person) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("model.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Person person0 = Person.restorePerson((-2643), "", "", true);
      assertEquals("", person0.getLastName());
      assertEquals("", person0.getFirstName());
      assertTrue(person0.isFemale());
      assertEquals((-2643), person0.getId());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertNotNull(person0);
      
      Person person1 = Person.restorePerson((-2643), "female", "female", true);
      assertEquals("female", person1.getLastName());
      assertEquals((-2643), person1.getId());
      assertEquals(1, person1.getGenderAsInt());
      assertTrue(person1.isFemale());
      assertEquals("female", person1.getFirstName());
      assertEquals("female", person1.getGender());
      assertNotSame(person1, person0);
      assertFalse(person1.equals((Object)person0));
      assertNotNull(person1);
      
      person0.addChild(person1);
      assertEquals("", person0.getLastName());
      assertEquals("", person0.getFirstName());
      assertTrue(person0.isFemale());
      assertEquals((-2643), person0.getId());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertEquals("female", person1.getLastName());
      assertEquals((-2643), person1.getId());
      assertEquals(1, person1.getGenderAsInt());
      assertTrue(person1.isFemale());
      assertEquals("female", person1.getFirstName());
      assertEquals("female", person1.getGender());
      assertNotSame(person0, person1);
      assertNotSame(person1, person0);
      assertFalse(person0.equals((Object)person1));
      assertFalse(person1.equals((Object)person0));
      
      Relation relation0 = person1.getRelation(person1);
      assertEquals("female", person1.getLastName());
      assertEquals((-2643), person1.getId());
      assertEquals(1, person1.getGenderAsInt());
      assertTrue(person1.isFemale());
      assertEquals("female", person1.getFirstName());
      assertEquals("female", person1.getGender());
      assertNotSame(person1, person0);
      assertFalse(person1.equals((Object)person0));
      assertNull(relation0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Person person0 = Person.restorePerson((-2643), "", "", true);
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertEquals("", person0.getFirstName());
      assertTrue(person0.isFemale());
      assertEquals((-2643), person0.getId());
      assertEquals("", person0.getLastName());
      assertNotNull(person0);
      
      Person person1 = new Person("E~:z2^Bo1.C=Yynq", "", true);
      assertTrue(person1.isFemale());
      assertEquals(2, person1.getId());
      assertEquals("female", person1.getGender());
      assertEquals("E~:z2^Bo1.C=Yynq", person1.getFirstName());
      assertEquals(1, person1.getGenderAsInt());
      assertEquals("", person1.getLastName());
      assertFalse(person1.equals((Object)person0));
      assertNotNull(person1);
      
      person0.addChild(person1);
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertEquals("", person0.getFirstName());
      assertTrue(person0.isFemale());
      assertEquals((-2643), person0.getId());
      assertEquals("", person0.getLastName());
      assertTrue(person1.isFemale());
      assertEquals(2, person1.getId());
      assertEquals("female", person1.getGender());
      assertEquals("E~:z2^Bo1.C=Yynq", person1.getFirstName());
      assertEquals(1, person1.getGenderAsInt());
      assertEquals("", person1.getLastName());
      assertNotSame(person0, person1);
      assertNotSame(person1, person0);
      assertFalse(person0.equals((Object)person1));
      assertFalse(person1.equals((Object)person0));
      
      Relation relation0 = person1.getRelation(person0);
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertEquals("", person0.getFirstName());
      assertTrue(person0.isFemale());
      assertEquals((-2643), person0.getId());
      assertEquals("", person0.getLastName());
      assertTrue(person1.isFemale());
      assertEquals(2, person1.getId());
      assertEquals("female", person1.getGender());
      assertEquals("E~:z2^Bo1.C=Yynq", person1.getFirstName());
      assertEquals(1, person1.getGenderAsInt());
      assertEquals("", person1.getLastName());
      assertNotSame(person0, person1);
      assertNotSame(person1, person0);
      assertFalse(person0.equals((Object)person1));
      assertFalse(person1.equals((Object)person0));
      assertNotNull(relation0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, true);
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals(1, person0.getId());
      assertNull(person0.getLastName());
      assertNull(person0.getFirstName());
      assertEquals("female", person0.getGender());
      assertNotNull(person0);
      
      Person person1 = new Person("]_saO42=Z8]'>d#", "", true);
      assertEquals("", person1.getLastName());
      assertEquals("]_saO42=Z8]'>d#", person1.getFirstName());
      assertEquals(1, person1.getGenderAsInt());
      assertEquals("female", person1.getGender());
      assertEquals(2, person1.getId());
      assertTrue(person1.isFemale());
      assertFalse(person1.equals((Object)person0));
      assertNotNull(person1);
      
      person1.addChild(person0);
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals(1, person0.getId());
      assertNull(person0.getLastName());
      assertNull(person0.getFirstName());
      assertEquals("female", person0.getGender());
      assertEquals("", person1.getLastName());
      assertEquals("]_saO42=Z8]'>d#", person1.getFirstName());
      assertEquals(1, person1.getGenderAsInt());
      assertEquals("female", person1.getGender());
      assertEquals(2, person1.getId());
      assertTrue(person1.isFemale());
      assertNotSame(person0, person1);
      assertNotSame(person1, person0);
      assertFalse(person0.equals((Object)person1));
      assertFalse(person1.equals((Object)person0));
      
      Person person2 = Person.restorePerson(0, "Wife", "female", true);
      assertTrue(person2.isFemale());
      assertEquals(0, person2.getId());
      assertEquals("female", person2.getLastName());
      assertEquals(1, person2.getGenderAsInt());
      assertEquals("Wife", person2.getFirstName());
      assertEquals("female", person2.getGender());
      assertNotSame(person2, person1);
      assertNotSame(person2, person0);
      assertFalse(person2.equals((Object)person1));
      assertFalse(person2.equals((Object)person0));
      assertNotNull(person2);
      
      person0.addChild(person2);
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals(1, person0.getId());
      assertNull(person0.getLastName());
      assertNull(person0.getFirstName());
      assertEquals("female", person0.getGender());
      assertTrue(person2.isFemale());
      assertEquals(0, person2.getId());
      assertEquals("female", person2.getLastName());
      assertEquals(1, person2.getGenderAsInt());
      assertEquals("Wife", person2.getFirstName());
      assertEquals("female", person2.getGender());
      assertNotSame(person0, person2);
      assertNotSame(person0, person1);
      assertNotSame(person2, person1);
      assertNotSame(person2, person0);
      assertFalse(person0.equals((Object)person2));
      assertFalse(person0.equals((Object)person1));
      assertFalse(person2.equals((Object)person1));
      assertFalse(person2.equals((Object)person0));
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "Father", "Father", true);
      assertEquals(0, person0.getId());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertEquals("Father", person0.getFirstName());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("Father", person0.getLastName());
      assertNotNull(person0);
      
      GregorianCalendar gregorianCalendar0 = person0.getDateOfBirth();
      assertEquals(0, person0.getId());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertEquals("Father", person0.getFirstName());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("Father", person0.getLastName());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertTrue(gregorianCalendar0.isLenient());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=?,MONTH=?,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=?,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=?,HOUR=?,HOUR_OF_DAY=?,MINUTE=?,SECOND=?,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      assertNotNull(gregorianCalendar0);
      
      gregorianCalendar0.setTimeInMillis(1L);
      assertEquals(0, person0.getId());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertEquals("Father", person0.getFirstName());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("Father", person0.getLastName());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertTrue(gregorianCalendar0.isLenient());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=1,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=1970,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=1,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      
      boolean boolean0 = person0.dateOfDeathEquals(gregorianCalendar0);
      assertEquals(0, person0.getId());
      assertEquals("female", person0.getGender());
      assertTrue(person0.isFemale());
      assertEquals("Father", person0.getFirstName());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("Father", person0.getLastName());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertTrue(gregorianCalendar0.isLenient());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=1,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=1970,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=1,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Person person0 = new Person("X", "X", false);
      assertEquals("male", person0.getGender());
      assertEquals(1, person0.getId());
      assertEquals("X", person0.getLastName());
      assertEquals("X", person0.getFirstName());
      assertEquals(0, person0.getGenderAsInt());
      assertFalse(person0.isFemale());
      assertNotNull(person0);
      
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar((-598), (-598), 1);
      assertNotNull(mockGregorianCalendar0);
      
      boolean boolean0 = person0.dateOfDeathEquals(mockGregorianCalendar0);
      assertEquals("male", person0.getGender());
      assertEquals(1, person0.getId());
      assertEquals("X", person0.getLastName());
      assertEquals("X", person0.getFirstName());
      assertEquals(0, person0.getGenderAsInt());
      assertFalse(person0.isFemale());
      assertEquals(1, mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, mockGregorianCalendar0.getFirstDayOfWeek());
      assertTrue(mockGregorianCalendar0.isLenient());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=-598,MONTH=-598,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=1,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", mockGregorianCalendar0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, true);
      assertNull(person0.getFirstName());
      assertEquals(1, person0.getId());
      assertTrue(person0.isFemale());
      assertEquals("female", person0.getGender());
      assertEquals(1, person0.getGenderAsInt());
      assertNull(person0.getLastName());
      assertNotNull(person0);
      
      GregorianCalendar gregorianCalendar0 = person0.getDateOfBirth();
      assertNull(person0.getFirstName());
      assertEquals(1, person0.getId());
      assertTrue(person0.isFemale());
      assertEquals("female", person0.getGender());
      assertEquals(1, person0.getGenderAsInt());
      assertNull(person0.getLastName());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=?,MONTH=?,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=?,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=?,HOUR=?,HOUR_OF_DAY=?,MINUTE=?,SECOND=?,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      assertTrue(gregorianCalendar0.isLenient());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertNotNull(gregorianCalendar0);
      
      gregorianCalendar0.add(1, (-1));
      assertNull(person0.getFirstName());
      assertEquals(1, person0.getId());
      assertTrue(person0.isFemale());
      assertEquals("female", person0.getGender());
      assertEquals(1, person0.getGenderAsInt());
      assertNull(person0.getLastName());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=1969,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      assertTrue(gregorianCalendar0.isLenient());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      
      boolean boolean0 = person0.dateOfDeathEquals(gregorianCalendar0);
      assertNull(person0.getFirstName());
      assertEquals(1, person0.getId());
      assertTrue(person0.isFemale());
      assertEquals("female", person0.getGender());
      assertEquals(1, person0.getGenderAsInt());
      assertNull(person0.getLastName());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=1969,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      assertTrue(gregorianCalendar0.isLenient());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "Father", "Father", true);
      assertTrue(person0.isFemale());
      assertEquals("Father", person0.getFirstName());
      assertEquals("Father", person0.getLastName());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertEquals(0, person0.getId());
      assertNotNull(person0);
      
      GregorianCalendar gregorianCalendar0 = person0.getDateOfBirth();
      assertTrue(person0.isFemale());
      assertEquals("Father", person0.getFirstName());
      assertEquals("Father", person0.getLastName());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertEquals(0, person0.getId());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=?,MONTH=?,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=?,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=?,HOUR=?,HOUR_OF_DAY=?,MINUTE=?,SECOND=?,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      assertTrue(gregorianCalendar0.isLenient());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertNotNull(gregorianCalendar0);
      
      boolean boolean0 = person0.dateOfDeathEquals(gregorianCalendar0);
      assertTrue(person0.isFemale());
      assertEquals("Father", person0.getFirstName());
      assertEquals("Father", person0.getLastName());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertEquals(0, person0.getId());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=?,MONTH=?,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=?,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=?,HOUR=?,HOUR_OF_DAY=?,MINUTE=?,SECOND=?,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      assertTrue(gregorianCalendar0.isLenient());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Person person0 = new Person("5>tiK1{GK,(P2@XK@B", "5>tiK1{GK,(P2@XK@B", false);
      assertEquals("5>tiK1{GK,(P2@XK@B", person0.getLastName());
      assertEquals("5>tiK1{GK,(P2@XK@B", person0.getFirstName());
      assertEquals(0, person0.getGenderAsInt());
      assertFalse(person0.isFemale());
      assertEquals(1, person0.getId());
      assertEquals("male", person0.getGender());
      assertNotNull(person0);
      
      boolean boolean0 = person0.dateOfDeathEquals((Calendar) null);
      assertEquals("5>tiK1{GK,(P2@XK@B", person0.getLastName());
      assertEquals("5>tiK1{GK,(P2@XK@B", person0.getFirstName());
      assertEquals(0, person0.getGenderAsInt());
      assertFalse(person0.isFemale());
      assertEquals(1, person0.getId());
      assertEquals("male", person0.getGender());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "Father", "Father", true);
      assertEquals(0, person0.getId());
      assertEquals("Father", person0.getFirstName());
      assertTrue(person0.isFemale());
      assertEquals("Father", person0.getLastName());
      assertEquals("female", person0.getGender());
      assertEquals(1, person0.getGenderAsInt());
      assertNotNull(person0);
      
      GregorianCalendar gregorianCalendar0 = person0.getDateOfBirth();
      assertEquals(0, person0.getId());
      assertEquals("Father", person0.getFirstName());
      assertTrue(person0.isFemale());
      assertEquals("Father", person0.getLastName());
      assertEquals("female", person0.getGender());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertTrue(gregorianCalendar0.isLenient());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=?,MONTH=?,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=?,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=?,HOUR=?,HOUR_OF_DAY=?,MINUTE=?,SECOND=?,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      assertNotNull(gregorianCalendar0);
      
      gregorianCalendar0.setTimeInMillis(1L);
      assertEquals(0, person0.getId());
      assertEquals("Father", person0.getFirstName());
      assertTrue(person0.isFemale());
      assertEquals("Father", person0.getLastName());
      assertEquals("female", person0.getGender());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=1,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=1970,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=1,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertTrue(gregorianCalendar0.isLenient());
      
      boolean boolean0 = person0.dateOfBirthEquals(gregorianCalendar0);
      assertEquals(0, person0.getId());
      assertEquals("Father", person0.getFirstName());
      assertTrue(person0.isFemale());
      assertEquals("Father", person0.getLastName());
      assertEquals("female", person0.getGender());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=1,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=1970,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=1,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertTrue(gregorianCalendar0.isLenient());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Person person0 = new Person("X", "X", false);
      assertFalse(person0.isFemale());
      assertEquals("male", person0.getGender());
      assertEquals(1, person0.getId());
      assertEquals("X", person0.getLastName());
      assertEquals("X", person0.getFirstName());
      assertEquals(0, person0.getGenderAsInt());
      assertNotNull(person0);
      
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar((-598), (-598), 1);
      assertNotNull(mockGregorianCalendar0);
      
      boolean boolean0 = person0.dateOfBirthEquals(mockGregorianCalendar0);
      assertFalse(person0.isFemale());
      assertEquals("male", person0.getGender());
      assertEquals(1, person0.getId());
      assertEquals("X", person0.getLastName());
      assertEquals("X", person0.getFirstName());
      assertEquals(0, person0.getGenderAsInt());
      assertEquals(1, mockGregorianCalendar0.getMinimalDaysInFirstWeek());
      assertEquals(1, mockGregorianCalendar0.getFirstDayOfWeek());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=-598,MONTH=-598,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=1,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", mockGregorianCalendar0.toString());
      assertTrue(mockGregorianCalendar0.isLenient());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, true);
      assertNull(person0.getFirstName());
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertNull(person0.getLastName());
      assertEquals(1, person0.getId());
      assertNotNull(person0);
      
      GregorianCalendar gregorianCalendar0 = person0.getDateOfBirth();
      assertNull(person0.getFirstName());
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertNull(person0.getLastName());
      assertEquals(1, person0.getId());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertTrue(gregorianCalendar0.isLenient());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=?,YEAR=?,MONTH=?,WEEK_OF_YEAR=?,WEEK_OF_MONTH=?,DAY_OF_MONTH=?,DAY_OF_YEAR=?,DAY_OF_WEEK=?,DAY_OF_WEEK_IN_MONTH=?,AM_PM=?,HOUR=?,HOUR_OF_DAY=?,MINUTE=?,SECOND=?,MILLISECOND=?,ZONE_OFFSET=?,DST_OFFSET=?]", gregorianCalendar0.toString());
      assertNotNull(gregorianCalendar0);
      
      gregorianCalendar0.add(1, (-1));
      assertNull(person0.getFirstName());
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertNull(person0.getLastName());
      assertEquals(1, person0.getId());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertTrue(gregorianCalendar0.isLenient());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=1969,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      
      boolean boolean0 = person0.dateOfBirthEquals(gregorianCalendar0);
      assertNull(person0.getFirstName());
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getGenderAsInt());
      assertEquals("female", person0.getGender());
      assertNull(person0.getLastName());
      assertEquals(1, person0.getId());
      assertEquals(1, gregorianCalendar0.getFirstDayOfWeek());
      assertEquals(1, gregorianCalendar0.getMinimalDaysInFirstWeek());
      assertTrue(gregorianCalendar0.isLenient());
      assertEquals("org.evosuite.runtime.mock.java.util.MockGregorianCalendar[time=?,areFieldsSet=false,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id=\"GMT\",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=1969,MONTH=0,WEEK_OF_YEAR=1,WEEK_OF_MONTH=1,DAY_OF_MONTH=1,DAY_OF_YEAR=1,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=1,AM_PM=0,HOUR=0,HOUR_OF_DAY=0,MINUTE=0,SECOND=0,MILLISECOND=0,ZONE_OFFSET=0,DST_OFFSET=0]", gregorianCalendar0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "Father", "Father", true);
      GregorianCalendar gregorianCalendar0 = person0.getDateOfBirth();
      boolean boolean0 = person0.dateOfBirthEquals(gregorianCalendar0);
      assertTrue(boolean0);
      assertEquals("Father", person0.getLastName());
      assertEquals(0, person0.getId());
      assertEquals("female", person0.getGender());
      assertEquals("Father", person0.getFirstName());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Person person0 = new Person("5>tiK1{GK,(P2@XK@B", "5>tiK1{GK,(P2@XK@B", false);
      boolean boolean0 = person0.dateOfBirthEquals((Calendar) null);
      assertEquals("5>tiK1{GK,(P2@XK@B", person0.getLastName());
      assertEquals(1, person0.getId());
      assertEquals("5>tiK1{GK,(P2@XK@B", person0.getFirstName());
      assertFalse(boolean0);
      assertEquals("male", person0.getGender());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, true);
      Locale locale0 = Locale.KOREA;
      Calendar calendar0 = MockCalendar.getInstance(locale0);
      boolean boolean0 = person0.dateOfBirthEquals(calendar0);
      assertFalse(boolean0);
      assertEquals(1, person0.getId());
      assertTrue(person0.isFemale());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, true);
      int int0 = person0.getGenderAsInt();
      assertEquals(1, person0.getId());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Person person0 = Person.restorePerson(1, "male", "male", false);
      int int0 = person0.getGenderAsInt();
      assertEquals(0, int0);
      assertEquals(1, person0.getId());
      assertEquals("male", person0.getFirstName());
      assertEquals("male", person0.getLastName());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, true);
      String string0 = person0.getGender();
      assertEquals("female", string0);
      assertEquals(1, person0.getId());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Person person0 = new Person("dsT$pK~-eS!{BTB_[*", "dsT$pK~-eS!{BTB_[*", false);
      String string0 = person0.getGender();
      assertEquals("dsT$pK~-eS!{BTB_[*", person0.getLastName());
      assertEquals("dsT$pK~-eS!{BTB_[*", person0.getFirstName());
      assertEquals("male", string0);
      assertEquals(1, person0.getId());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Person person0 = Person.restorePerson((-2643), "", "", true);
      Person person1 = Person.restorePerson((-2643), "female", "female", true);
      person0.addChild(person1);
      person0.getChildren();
      assertEquals((-2643), person0.getId());
      assertEquals("", person0.getLastName());
      assertEquals("", person0.getFirstName());
      assertTrue(person0.isFemale());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Person person0 = Person.restorePerson((-1415), ")'>c{eS=&Wx1Mu", (String) null, false);
      person0.getChildren();
      assertEquals((-1415), person0.getId());
      assertEquals(")'>c{eS=&Wx1Mu", person0.getFirstName());
      assertFalse(person0.isFemale());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, true);
      Person person1 = new Person("female", "female", true);
      Person person2 = Person.restorePerson((-513), (String) null, "male", true);
      person0.addChild(person2);
      boolean boolean0 = person2.removeRelation(person1);
      assertFalse(boolean0);
      assertEquals("female", person1.getLastName());
      assertEquals((-513), person2.getId());
      assertEquals(2, person1.getId());
      assertEquals("female", person1.getFirstName());
      assertEquals("male", person2.getLastName());
      assertEquals(1, person2.getGenderAsInt());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Person person0 = Person.restorePerson(0, "Relation exists or is illegal", "Relation exists or is illegal", true);
      Person person1 = Person.restorePerson(0, "male", "=jNu}vH|nzlU L0A#1y", true);
      person0.addSpouse(person1);
      assertEquals("=jNu}vH|nzlU L0A#1y", person1.getLastName());
      assertEquals("male", person1.getFirstName());
      
      Relation relation0 = person0.getRelation((Person) null);
      assertEquals(0, person0.getId());
      assertEquals("Relation exists or is illegal", person0.getFirstName());
      assertNull(relation0);
      assertEquals(1, person0.getGenderAsInt());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, true);
      Person person1 = new Person((String) null, (String) null, true);
      person0.addSpouse(person1);
      Relation relation0 = person0.getRelation(person1);
      assertEquals(2, person1.getId());
      assertNotNull(relation0);
      assertTrue(person1.isFemale());
      assertEquals(1, person0.getId());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Person person0 = new Person(" ]/mc 14yqz", " ]/mc 14yqz", true);
      Person person1 = Person.restorePerson((-2094), "female", " ]/mc 14yqz", true);
      Person person2 = new Person("female", "female", true);
      person2.addChild(person1);
      person2.addChild(person0);
      try { 
        person0.addSpouse(person1);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Relation exists or is illegal
         //
         verifyException("model.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Person person0 = new Person("Fathr", "Fathr", true);
      Person person1 = Person.restorePerson(0, "female", "female", true);
      Person person2 = new Person("female", "female", true);
      person1.addChild(person2);
      person0.addSpouse(person1);
      assertEquals("female", person1.getLastName());
      assertTrue(person1.isFemale());
      assertEquals(0, person1.getId());
      assertEquals("female", person1.getFirstName());
      
      person2.addChild(person0);
      assertEquals(3, person2.getId());
      assertEquals("Fathr", person0.getFirstName());
      assertEquals("Fathr", person0.getLastName());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Person person0 = new Person("dsT$pK~-eS!{BTB_[*", "dsT$pK~-eS!{BTB_[*", false);
      Person person1 = new Person("female", "female", false);
      person0.addSpouse(person1);
      assertEquals(2, person1.getId());
      
      Person person2 = Person.restorePerson((-860), "dsT$pK~-eS!{BTB_[*", "dsT$pK~-eS!{BTB_[*", false);
      person0.addSpouse(person2);
      assertEquals("dsT$pK~-eS!{BTB_[*", person2.getLastName());
      assertEquals("dsT$pK~-eS!{BTB_[*", person2.getFirstName());
      assertEquals((-860), person2.getId());
      assertEquals(0, person2.getGenderAsInt());
      assertEquals("dsT$pK~-eS!{BTB_[*", person0.getFirstName());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, true);
      Person person1 = new Person("female", "female", true);
      person1.addChild(person0);
      Person person2 = Person.restorePerson((-513), (String) null, "male", true);
      person0.addChild(person2);
      person1.addSpouse(person2);
      assertEquals("female", person1.getFirstName());
      assertEquals("male", person2.getLastName());
      assertEquals((-513), person2.getId());
      assertEquals(2, person1.getId());
      assertEquals("female", person1.getLastName());
      assertEquals("female", person2.getGender());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, true);
      Person person1 = new Person("female", "female", true);
      person1.addChild(person0);
      try { 
        person0.addChild(person1);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Relation exists or is illegal
         //
         verifyException("model.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Person person0 = new Person("", "", false);
      Person person1 = Person.restorePerson(1168, "", "", true);
      person1.addSpouse(person0);
      assertEquals("", person1.getFirstName());
      assertEquals(1168, person1.getId());
      assertEquals("", person1.getLastName());
      assertEquals("female", person1.getGender());
      
      person0.getChildren();
      assertEquals(1, person0.getId());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Person person0 = new Person("dsT$pK~-eS!{BTB_[*", "dsT$pK~-eS!{BTB_[*", false);
      try { 
        person0.addSpouse(person0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Relation exists or is illegal
         //
         verifyException("model.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Person person0 = new Person((String) null, "", false);
      Person person1 = Person.restorePerson(0, ":`wj=2S>/aB", " ", false);
      person1.addChild(person0);
      boolean boolean0 = person0.removeRelation(person1);
      assertEquals(" ", person1.getLastName());
      assertEquals(1, person0.getId());
      assertTrue(boolean0);
      assertEquals(":`wj=2S>/aB", person1.getFirstName());
      assertEquals(0, person1.getGenderAsInt());
      assertEquals(0, person1.getId());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Person person0 = new Person("dsT$pK~-eS!{BTB_[*", "dsT$pK~-eS!{BTB_[*", false);
      int int0 = person0.getId();
      assertEquals(1, int0);
      assertEquals("dsT$pK~-eS!{BTB_[*", person0.getFirstName());
      assertEquals("dsT$pK~-eS!{BTB_[*", person0.getLastName());
      assertFalse(person0.isFemale());
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Person person0 = new Person("dsT$pK~-eS!{BTB_[*", "dsT$pK~-eS!{BTB_[*", false);
      String string0 = person0.getFirstName();
      assertEquals(1, person0.getId());
      assertEquals("dsT$pK~-eS!{BTB_[*", string0);
      assertEquals("dsT$pK~-eS!{BTB_[*", person0.getLastName());
      assertEquals("male", person0.getGender());
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, true);
      String string0 = person0.toString();
      assertEquals(1, person0.getId());
      assertEquals("null null", string0);
      assertTrue(person0.isFemale());
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Person person0 = new Person("", "", false);
      person0.setLastName("");
      assertEquals("", person0.getFirstName());
      assertEquals("", person0.getLastName());
      assertFalse(person0.isFemale());
      assertEquals(1, person0.getId());
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Person person0 = new Person("Fathr", "Fathr", true);
      MockGregorianCalendar mockGregorianCalendar0 = new MockGregorianCalendar();
      boolean boolean0 = person0.dateOfDeathEquals(mockGregorianCalendar0);
      assertEquals("Fathr", person0.getFirstName());
      assertEquals("Fathr", person0.getLastName());
      assertTrue(person0.isFemale());
      assertEquals(1, person0.getId());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Person person0 = new Person("ZH", "ZH", false);
      String string0 = person0.getLastName();
      assertEquals(1, person0.getId());
      assertEquals("ZH", person0.getFirstName());
      assertEquals("ZH", string0);
      assertFalse(person0.isFemale());
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      Person person0 = new Person((String) null, (String) null, false);
      person0.setFemale(false);
      assertEquals(1, person0.getId());
      assertEquals(0, person0.getGenderAsInt());
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Person person0 = new Person("", "", false);
      person0.getRelationships();
      assertEquals("", person0.getFirstName());
      assertEquals("", person0.getLastName());
      assertFalse(person0.isFemale());
      assertEquals(1, person0.getId());
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Person person0 = new Person("", "", false);
      person0.setFirstName("");
      assertEquals("", person0.getFirstName());
      assertEquals("", person0.getLastName());
      assertEquals(1, person0.getId());
      assertEquals(0, person0.getGenderAsInt());
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Person person0 = new Person("", "", false);
      boolean boolean0 = person0.isFemale();
      assertEquals(1, person0.getId());
      assertEquals("", person0.getFirstName());
      assertEquals("", person0.getLastName());
      assertFalse(boolean0);
  }
}
